language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt5:/usr/local/opt/openssl
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env:
        - CMAKE_PREFIX_PATH=/usr/local/opt/qt5:/usr/local/opt/openssl
      
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew reinstall cmake qt5 python3 qscintilla2 openssl git;
      cd ext
      ./gen_distorm.sh
      cd ..
    else
      sudo apt-get -qq update;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DALL=ON -DWITH_SCINTILLA=ON

script: make

addons:
  apt:
    packages:
    - cmake
    - python2.7-dev
    - python3-dev
    - libqt5svg5-dev
    - qt5-default
    - libqt5xmlpatterns5-dev
    - git
    - libssl-dev
    - libdistorm3-dev
    - libqt5scintilla2-dev
