version: 3.4.1.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: 'C:\Qt\5.11.1\msvc2017_64'
      PATH: '%QTDIR%\bin;%PATH%'
      compiler: vs2017
      platform: x64
      config: Release

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- git submodule update --init --recursive
- powershell -command "msbuild ext\distorm\make\win32\distorm.sln  /p:Configuration=dll /p:Platform=x64 /p:PlatformToolset=v141"
- appveyor DownloadFile https://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.10.7/QScintilla_gpl-2.10.7.zip
- 7z x .\QScintilla_gpl-2.10.7.zip -o.\ext\
- ps: ren ext\QScintilla_gpl-2.10.7 QScintilla_gpl
- ps: pushd ext\QScintilla_gpl\Qt4Qt5
- qmake
- nmake
- ps: popd
- ps: popd
- ps: popd

before_build:
- mkdir build
- cd build
- cmake ../ -DALL=ON -DWITH_SCINTILLA=ON -G "NMake Makefiles" "-DCMAKE_PREFIX_PATH=%QTDIR%"

build_script:
- nmake
- cd ..

after_build:
- win_package.bat 2017_64

