version: 3.4.1.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      compiler: vs2017
      platform: x64
      config: Release

install:
- git submodule update --init --recursive
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
- mkdir build
- cd build
- cmake ../ -DBASIC=ON -DWITH_OPENSSL=ON -G "NMake Makefiles" "-DCMAKE_PREFIX_PATH=%QTDIR%"

build_script:
- nmake

